### ISSUE TITLE
practica 2

### ISSUE THREAD

**Issue by ang3-l32** [SistemasTecTlaxiaco/practica-de-interfaz-grafica-en-visual-sutdio-app-topicos4semestre2022#2]
[Practica 2 Topicos avanzados de programación (1).pdf](https://github.com/SistemasTecTlaxiaco/practica-de-interfaz-grafica-en-visual-sutdio-app-topicos4semestre2022/files/8105397/Practica.2.Topicos.avanzados.de.programacion.1.pdf)

**Comment by josealfredo79** [comment]
y la calificación

**Comment by josealfredo79** [comment]
no esta la calificación

**Comment by JudithReynaCS** [comment]
Calificacion:17
